"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("element", [
      { 
        id: 1,
        lesson_id: 1,
        type: 'text',
        order: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 2,
        lesson_id: 1,
        type: 'image',
        order: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 3,
        lesson_id: 1,
        type: 'text',
        order: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 4,
        lesson_id: 1,
        type: 'text',
        order: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 5,
        lesson_id: 1,
        type: 'text',
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 6,
        lesson_id: 1,
        type: 'image',
        order: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 7,
        lesson_id: 1,
        type: 'text',
        order: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 8,
        lesson_id: 9,
        type: 'image',
        order: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 9,
        lesson_id: 9,
        type: 'text',
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 10,
        lesson_id: 9,
        type: 'text',
        order: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 11,
        lesson_id: 9,
        type: 'text',
        order: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 12,
        lesson_id: 9,
        type: 'text',
        order: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 13,
        lesson_id: 9,
        type: 'text',
        order: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 14,
        lesson_id: 10,
        type: 'text',
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 15,
        lesson_id: 10,
        type: 'text',
        order: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 16,
        lesson_id: 10,
        type: 'image',
        order: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 17,
        lesson_id: 10,
        type: 'text',
        order: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 18,
        lesson_id: 10,
        type: 'text',
        order: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 19,
        lesson_id: 12,
        type: 'text',
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 20,
        lesson_id: 12,
        type: 'image',
        order: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 21,
        lesson_id: 12,
        type: 'text',
        order: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 22,
        lesson_id: 12,
        type: 'text',
        order: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 23,
        lesson_id: 12,
        type: 'text',
        order: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 24,
        lesson_id: 3,
        type: 'text',
        order: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 25,
        lesson_id: 3,
        type: 'text',
        order: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 26,
        lesson_id: 3,
        type: 'image',
        order: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 27,
        lesson_id: 3,
        type: 'text',
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 28,
        lesson_id: 3,
        type: 'text',
        order: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 29,
        lesson_id: 6,
        type: 'image',
        order: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 30,
        lesson_id: 6,
        type: 'text',
        order: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 31,
        lesson_id: 6,
        type: 'text',
        order: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 32,
        lesson_id: 6,
        type: 'text',
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 33,
        lesson_id: 6,
        type: 'text',
        order: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 34,
        lesson_id: 6,
        type: 'text',
        order: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 35,
        lesson_id: 6,
        type: 'image',
        order: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 36,
        lesson_id: 7,
        type: 'text',
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 37,
        lesson_id: 7,
        type: 'text',
        order: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 38,
        lesson_id: 7,
        type: 'text',
        order: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 39,
        lesson_id: 7,
        type: 'image',
        order: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 40,
        lesson_id: 8,
        type: 'image',
        order: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 41,
        lesson_id: 8,
        type: 'text',
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 42,
        lesson_id: 8,
        type: 'text',
        order: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 43,
        lesson_id: 8,
        type: 'text',
        order: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 44,
        lesson_id: 4,
        type: 'text',
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 45,
        lesson_id: 4,
        type: 'text',
        order: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 46,
        lesson_id: 4,
        type: 'text',
        order: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 47,
        lesson_id: 4,
        type: 'image',
        order: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 48,
        lesson_id: 2,
        type: 'text',
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 49,
        lesson_id: 2,
        type: 'text',
        order: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 50,
        lesson_id: 2,
        type: 'text',
        order: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 51,
        lesson_id: 2,
        type: 'image',
        order: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 52,
        lesson_id: 7,
        type: 'text',
        order: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 53,
        lesson_id: 7,
        type: 'text',
        order: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 54,
        lesson_id: 7,
        type: 'image',
        order: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 55,
        lesson_id: 7,
        type: 'text',
        order: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 56,
        lesson_id: 7,
        type: 'text',
        order: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 57,
        lesson_id: 7,
        type: 'image',
        order: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 58,
        lesson_id: 7,
        type: 'text',
        order: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 59,
        lesson_id: 7,
        type: 'image',
        order: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 60,
        lesson_id: 7,
        type: 'text',
        order: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 61,
        lesson_id: 5,
        type: 'text',
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 62,
        lesson_id: 5,
        type: 'text',
        order: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 63,
        lesson_id: 5,
        type: 'text',
        order: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 64,
        lesson_id: 5,
        type: 'text',
        order: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 65,
        lesson_id: 5,
        type: 'text',
        order: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 66,
        lesson_id: 5,
        type: 'text',
        order: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 67,
        lesson_id: 11,
        type: 'text',
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 68,
        lesson_id: 11,
        type: 'text',
        order: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 69,
        lesson_id: 11,
        type: 'text',
        order: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 70,
        lesson_id: 11,
        type: 'text',
        order: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 71,
        lesson_id: 11,
        type: 'text',
        order: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 72,
        lesson_id: 11,
        type: 'text',
        order: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
    ], {})
  },

  async down (queryInterface, Sequelize) {
    return queryInterface.bulkDelete('element', null, {});
  }
}