"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("lesson", [
      { 
        id: 1,
        cursus_id: 1,
        name: "Dynamiser votre site avec Javascript",
        price: 32,
        order: 2,
        createdAt: new Date(Date.now() - (1000 * 3600 * 145)),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: 2,
      },
      { 
        id: 2,
        cursus_id: 2,
        name: "Mettre en oeuvre le style dans l'assiette",
        price: 26,
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 3,
        cursus_id: 4,
        name: "Les saveurs",
        price: 23,
        order: 2,
        createdAt: new Date(Date.now() - (1000 * 3600 * 230)),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: 1,
      },
      { 
        id: 4,
        cursus_id: 6,
        name: "Découverte de l'instrument",
        price: 26,
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 5,
        cursus_id: 6,
        name: "Les accords et les gammes",
        price: 26,
        order: 2,
        createdAt: new Date(Date.now() - (1000 * 3600 * 95)),
        updatedAt: new Date(),
        createdBy: 2,
        updatedBy: 2,
      },
      { 
        id: 6,
        cursus_id: 1,
        name: "Les langages Html et CSS",
        price: 32,
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 7,
        cursus_id: 2,
        name: "Harmoniser un repas à quatre plats",
        price: 26,
        order: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 2,
        updatedBy: null,
      },
      { 
        id: 8,
        cursus_id: 5,
        name: "Les outils du jardinier",
        price: 16,
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 9,
        cursus_id: 5,
        name: "Jardiner avec la lune",
        price: 16,
        order: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 2,
        updatedBy: null,
      },
      { 
        id: 10,
        cursus_id: 4,
        name: "Les modes de cuisson",
        price: 23,
        order: 1,
        createdAt: new Date(Date.now() - (1000 * 3600 * 162)),
        updatedAt: new Date(),
        createdBy: 2,
        updatedBy: 1,
      },
      { 
        id: 11,
        cursus_id: 3,
        name: "Les accords et les gammes",
        price: 26,
        order: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 12,
        cursus_id: 3,
        name: "Découverte de l'instrument",
        price: 26,
        order: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 2,
        updatedBy: null,
      },
    ], {})
  },

  async down (queryInterface, Sequelize) {
    return queryInterface.bulkDelete('lesson', null, {});
  }
}