"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("text", [
      { 
        id: 1,
        element_id: 1,
        type: 'title2',
        content: 'Les conditions',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 2,
        element_id: 3,
        type: 'title2',
        content: 'Les variables',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 3,
        element_id: 4,
        type: 'paragraph',
        content: 'loremLorem ipsum, dolor sit amet consectetur adipisicing elit. Quae veniam nobis facere quia delectus corrupti soluta voluptatem doloremque doloribus atque fugiat, aperiam officiis culpa? Consequuntur incidunt veritatis odit repellat dolores.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 4,
        element_id: 5,
        type: 'title1',
        content: 'Les bases',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 5,
        element_id: 7,
        type: 'paragraph',
        content: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Voluptatum molestiae numquam cum sed quod aliquid veniam minima earum quidem corporis distinctio illo, suscipit omnis ullam nulla. Nisi sit accusantium consequatur?',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 6,
        element_id: 9,
        type: 'title1',
        content: 'La Lune',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 7,
        element_id: 10,
        type: 'title2',
        content: 'Le cycle lunaire',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 8,
        element_id: 11,
        type: 'paragraph',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed dictum tellus. Suspendisse potenti. Phasellus vel tellus quis arcu porta ornare a in elit. Fusce sit amet feugiat nisl. Integer porta tellus ligula, ut lobortis mi tempor eget. Pellentesque tincidunt sem nulla, sit amet dictum diam viverra sed. Sed vestibulum felis mi, id consectetur sapien accumsan quis. Pellentesque mattis purus ut urna pulvinar tempus. Mauris ac nisl tellus. Praesent ut vulputate massa.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 9,
        element_id: 12,
        type: 'paragraph',
        content: 'Maecenas scelerisque condimentum sem, eu accumsan nisl tempor vel. Nulla imperdiet, diam et tempus vestibulum, quam ligula elementum lectus, id consequat ipsum orci et tortor. Suspendisse turpis elit, tempus et dui id, condimentum dictum nibh. Maecenas mattis a est at ultrices. Maecenas id turpis rutrum, consectetur erat ac, tincidunt mi. Cras vestibulum fringilla nisi a ultricies. Pellentesque sagittis ante et massa dignissim, in hendrerit eros aliquam. Cras enim leo, semper vitae tellus id, blandit fermentum nulla. Etiam a rutrum eros. Mauris eget rutrum sem, ac mollis nibh. Curabitur imperdiet mauris eget facilisis interdum. Praesent at tortor sed magna pulvinar euismod eget nec neque. Morbi ac fringilla nisl, id tempor felis.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 10,
        element_id: 13,
        type: 'paragraph',
        content: 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus convallis sollicitudin dui in euismod. Aliquam sit amet lacus posuere, eleifend sem id, luctus libero. Proin iaculis elit at neque pellentesque gravida. Nunc vestibulum aliquam risus nec congue. Nam et nisi et purus semper sagittis. Aenean sit amet urna iaculis nisi egestas aliquet in quis velit. Curabitur molestie diam sed nulla luctus pharetra. Cras sed malesuada nisl. Proin quis justo nec metus lacinia porttitor. Maecenas facilisis mauris quis porta scelerisque. Sed tincidunt nunc in volutpat iaculis. Nulla euismod, dui id porttitor maximus, arcu purus luctus erat, vitae iaculis neque ipsum at ante.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 11,
        element_id: 14,
        type: 'title1',
        content: 'Introduction',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 12,
        element_id: 15,
        type: 'title2',
        content: 'Les différents modes de cuisson',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 13,
        element_id: 17,
        type: 'paragraph',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce nec nunc id urna blandit pretium. Pellentesque enim est, aliquet at mauris eget, mattis aliquam risus. Morbi eu leo semper, placerat tortor vel, tempor nulla. Integer laoreet semper consequat. Aenean auctor lobortis magna non fermentum. Integer neque leo, consectetur ut blandit quis, finibus in quam. Pellentesque fermentum sed tortor dapibus accumsan. Donec nec arcu ante. Suspendisse potenti. Aliquam erat volutpat. Etiam tempus neque ac sollicitudin fringilla. Donec blandit nibh lacus, sed aliquam nunc viverra id.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 14,
        element_id: 18,
        type: 'paragraph',
        content: 'Morbi sollicitudin volutpat lobortis. Morbi tellus enim, blandit vel dignissim et, tristique a neque. Donec sagittis nulla nec leo mollis vestibulum. Maecenas ut viverra purus. Aenean molestie, libero in semper convallis, dui sem scelerisque dui, sed tristique nisi libero et sapien. Fusce mi lacus, porttitor nec sem id, lobortis interdum quam. Nam vitae metus eu nunc aliquet hendrerit. Nam suscipit laoreet ipsum, mattis sodales ex gravida non. Phasellus dapibus metus ipsum, at euismod dolor mattis sed. Sed nisl turpis, suscipit non vestibulum non, sollicitudin vitae magna. Sed ac pretium est. Nullam blandit condimentum turpis, vel venenatis mi sagittis semper. Suspendisse non lectus neque. Nam pretium pulvinar nibh vel dictum.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 15,
        element_id: 19,
        type: 'title1',
        content: 'Introduction',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 16,
        element_id: 21,
        type: 'title2',
        content: 'Anatomie de la guitare',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 17,
        element_id: 22,
        type: 'paragraph',
        content: 'Sed elementum lectus nec justo interdum, eget hendrerit tortor dignissim. Donec facilisis sodales lorem ac volutpat. Maecenas vestibulum vestibulum arcu, eget euismod sapien facilisis at. Phasellus vitae dui eget nulla viverra ultrices. Sed eros purus, gravida a pellentesque vel, iaculis quis purus. Praesent et velit at ipsum interdum congue ut eget arcu. Vestibulum dolor justo, cursus vel lobortis sed, dictum ut ex. Praesent placerat facilisis lacus eget semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras tempus, justo ut convallis porttitor, orci ipsum dapibus nibh, sed auctor felis est nec nisl. Nunc vel pharetra libero. Nullam convallis nunc non arcu congue, eu tempus metus placerat. Donec ac laoreet massa, ut egestas ex.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 18,
        element_id: 23,
        type: 'paragraph',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque luctus semper ipsum, et ultricies orci rhoncus a. Duis dui orci, faucibus eget accumsan in, aliquam vitae velit. Vivamus massa nulla, cursus condimentum sem a, dignissim vulputate est. Quisque at cursus orci. Nam at laoreet massa, pulvinar fringilla purus. Nullam eget massa odio. Sed placerat elit metus, et accumsan turpis interdum et. Donec pretium tristique enim vel fringilla. Etiam interdum pharetra massa, in dapibus leo dignissim non. Aliquam varius risus ac nunc lacinia venenatis.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 19,
        element_id: 24,
        type: 'paragraph',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus augue ut magna faucibus sagittis. Cras posuere hendrerit mattis. Nulla eu massa egestas nunc rutrum pretium at eget libero. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris ornare consectetur nisi non volutpat. Mauris imperdiet laoreet egestas. Mauris dignissim nibh eget tempor ornare.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 20,
        element_id: 25,
        type: 'paragraph',
        content: 'Pellentesque vehicula orci ut elit feugiat faucibus. Aenean et mi ligula. In hac habitasse platea dictumst. Pellentesque dolor metus, hendrerit maximus tempor eget, dictum ac urna. Sed eu lectus ullamcorper, consectetur enim in, fermentum tellus. Vivamus malesuada mi non elit faucibus maximus. In elementum nibh vestibulum feugiat aliquet. Phasellus dapibus condimentum velit ac rutrum. Donec luctus, mauris a mollis faucibus, magna felis ultrices mauris, eu faucibus orci lectus gravida metus. Suspendisse aliquet nibh dolor, vel dapibus lectus laoreet et. Pellentesque dignissim sit amet risus ut tincidunt. Phasellus ut orci vitae mi lacinia euismod ac sit amet ligula. Fusce massa ligula, auctor vel velit id, posuere aliquam magna. Ut aliquet eros eros.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 21,
        element_id: 27,
        type: 'title1',
        content: 'Introduction',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 22,
        element_id: 28,
        type: 'title2',
        content: 'Présentation des goûts',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 23,
        element_id: 30,
        type: 'title2',
        content: 'Le HTML',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 24,
        element_id: 31,
        type: 'title2',
        content: 'Le CSS',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 25,
        element_id: 32,
        type: 'title1',
        content: 'Introduction',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 26,
        element_id: 33,
        type: 'paragraph',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sit amet dolor sagittis elit ullamcorper sollicitudin vel vitae enim. Fusce non volutpat lectus. Vivamus pellentesque libero metus, eget pretium mauris pharetra tempor. Curabitur vitae placerat quam. Maecenas non metus mollis, cursus justo id, aliquet ante. Donec felis nisl, sodales eget odio eget, sodales malesuada dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed semper, justo a cursus fringilla, risus neque vulputate lacus, at accumsan est diam mollis quam. Integer elementum nibh ac magna dapibus, sed rutrum sapien finibus. Nam sed velit vel nisi tincidunt tristique. Integer finibus mauris sed scelerisque euismod. In luctus ex nec justo consectetur, sed commodo purus mollis. Integer eu justo vitae quam laoreet tincidunt vel et ex. Vivamus eget tincidunt nisl. Sed commodo sed tortor et elementum. Proin facilisis, sapien non lobortis commodo, ipsum lorem consectetur enim, ut dapibus leo ex nec ante.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 27,
        element_id: 34,
        type: 'paragraph',
        content: 'Duis egestas pellentesque tristique. Donec vitae cursus leo. Cras a commodo nulla. Maecenas felis dolor, accumsan at mauris rutrum, imperdiet tempus eros. Maecenas imperdiet tortor sit amet nibh tempus varius. In et pellentesque dui, congue auctor sapien. Morbi blandit consequat erat, in porta turpis faucibus sit amet. Suspendisse ornare, urna in consequat rutrum, libero sapien imperdiet nibh, eget euismod libero odio vitae ligula. Fusce at justo sodales, mattis lacus ac, varius ex. Fusce urna risus, varius rutrum condimentum id, tristique ac nisl. Duis vitae scelerisque erat. Aliquam erat volutpat. Donec consectetur justo ligula. Nam blandit risus et volutpat eleifend. Nulla bibendum mi vel dignissim hendrerit.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 28,
        element_id: 36,
        type: 'title1',
        content: 'Présentation des quatre plats',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 29,
        element_id: 37,
        type: 'title2',
        content: "Le hors d'oeuvre",
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 30,
        element_id: 38,
        type: 'paragraph',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam id pharetra turpis, eget mattis ex. Integer fermentum, felis efficitur malesuada tincidunt, mi eros condimentum diam, ac ultrices turpis mauris sit amet massa. Maecenas at risus ipsum. Suspendisse interdum cursus facilisis. Sed aliquet eros in massa vulputate, quis molestie nulla porttitor. Donec nisi odio, viverra quis metus sit amet, convallis auctor odio. Curabitur iaculis neque aliquam quam dignissim, id accumsan ante sollicitudin. Nunc vitae lorem augue. Donec ut hendrerit eros, eu commodo ligula.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 31,
        element_id: 41,
        type: 'title1',
        content: 'Introduction',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 32,
        element_id: 42,
        type: 'paragraph',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sit amet lobortis quam. Suspendisse tempor tempus libero, ac facilisis nisl tempor aliquet. Nunc elit velit, commodo elementum venenatis quis, accumsan in ipsum. Donec finibus, dui at varius rhoncus, metus metus facilisis risus, nec ultrices tortor orci id purus. Curabitur vehicula convallis tempor. Proin vitae pulvinar felis, at convallis ligula. Sed in lacinia orci. In gravida et felis at bibendum.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 33,
        element_id: 43,
        type: 'title2',
        content: 'Les différents outils',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 34,
        element_id: 44,
        type: 'title1',
        content: 'Introduction',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 35,
        element_id: 45,
        type: 'title2',
        content: 'Le piano',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 36,
        element_id: 46,
        type: 'paragraph',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed feugiat justo eu magna rhoncus, ac hendrerit urna imperdiet. Maecenas ut ultrices est. Duis pellentesque sollicitudin justo eu condimentum. Nullam finibus odio eget mauris ornare finibus. Suspendisse sed massa dui. Integer faucibus enim nibh, id lobortis eros pellentesque quis. Maecenas sed tellus vitae magna dictum feugiat. Nam tristique odio et ex mattis porttitor. Integer ac pulvinar ex, nec sollicitudin augue. Maecenas pharetra elit non congue faucibus. Aliquam erat volutpat. Donec nec neque lectus. Pellentesque velit est, congue in tincidunt ac, suscipit vitae neque. Sed sit amet interdum ligula, ac commodo urna. Etiam tellus nisl, fermentum ut eros eu, maximus porttitor nulla.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 37,
        element_id: 48,
        type: 'title1',
        content: 'Introduction',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 38,
        element_id: 49,
        type: 'title2',
        content: 'Les assiettes',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 39,
        element_id: 50,
        type: 'paragraph',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sem ex, egestas nec lorem id, tincidunt auctor augue. Cras euismod, magna eu volutpat ornare, diam ipsum pellentesque orci, non pellentesque nisi leo rhoncus velit. Suspendisse nec ligula sed risus imperdiet faucibus id quis ipsum. Integer tempor aliquet eros, eget malesuada quam finibus eget. Nullam turpis nunc, viverra non ipsum et, accumsan consectetur urna. Proin consectetur accumsan arcu non finibus. Donec at ante lectus. Nulla eleifend, metus vel scelerisque placerat, eros nulla finibus sapien, eget ultrices metus eros quis enim. Vivamus erat elit, fermentum vitae lectus porta, laoreet interdum nisl.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 40,
        element_id: 52,
        type: 'title2',
        content: "L'entrée",
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 41,
        element_id: 53,
        type: 'paragraph',
        content: 'Duis a quam tristique, ullamcorper sapien et, gravida ex. Nullam dictum ullamcorper felis. Proin tincidunt dictum ipsum, vitae sollicitudin erat imperdiet pharetra. Nunc a faucibus magna, in porttitor ante. Ut sed orci bibendum, tempus felis nec, maximus metus. Pellentesque at dui id dolor pulvinar semper ac pulvinar felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras eu nibh interdum, sodales ex ut, aliquam diam.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 42,
        element_id: 55,
        type: 'title2',
        content: 'Le plat',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 43,
        element_id: 56,
        type: 'paragraph',
        content: 'Phasellus vitae tellus orci. Integer pellentesque, augue sit amet pulvinar pretium, lacus sapien porttitor metus, dapibus lobortis est ex sed ipsum. Etiam malesuada nunc vitae nisl ultrices luctus. Pellentesque nibh ante, rhoncus eu justo et, laoreet tempus arcu. Mauris faucibus ante vel placerat venenatis. Quisque facilisis a sapien ac lacinia. Sed rhoncus risus vitae metus dignissim feugiat. Quisque ullamcorper mi quis lectus ornare, vitae venenatis sem aliquam. Cras leo turpis, tempus eu pretium at, maximus et risus. Fusce nec enim molestie ante sollicitudin blandit sed sit amet dolor. Fusce vitae enim sed lectus placerat tempor. Donec sodales finibus purus nec commodo. Sed vulputate molestie turpis ut hendrerit.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 44,
        element_id: 58,
        type: 'title2',
        content: 'Le dessert',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 45,
        element_id: 60,
        type: 'paragraph',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean justo tellus, elementum sit amet scelerisque vel, finibus sit amet ante. Maecenas eu pretium libero, eu molestie tortor. Nulla sagittis nibh in ipsum commodo, in hendrerit magna ultrices. Nullam nec augue risus. Curabitur cursus, felis at ultrices ornare, enim tellus scelerisque mi, id sodales sapien odio sed urna. Sed nec dapibus leo, eu blandit metus. Aenean lacinia felis dui, nec fringilla velit iaculis in. Suspendisse potenti.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 46,
        element_id: 61,
        type: 'title1',
        content: 'Introduction',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 47,
        element_id: 62,
        type: 'title2',
        content: 'Les accords',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 48,
        element_id: 63,
        type: 'paragraph',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi tempor, dui et viverra porta, mauris urna feugiat eros, hendrerit feugiat turpis erat ut libero. Aliquam et pretium tellus, at suscipit neque. Quisque vestibulum efficitur mi, sed luctus sem pharetra vitae. Phasellus malesuada tempor varius. Donec quis posuere lacus. Sed lacinia, dui aliquet porttitor porta, erat nunc pharetra tellus, a tincidunt erat urna in elit. Suspendisse sit amet nulla placerat, tincidunt risus non, elementum ante. Duis leo arcu, porta in auctor sit amet, varius at nulla. Morbi sed mauris et diam sollicitudin volutpat a et ipsum.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 49,
        element_id: 64,
        type: 'title2',
        content: 'Les gammes',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 50,
        element_id: 65,
        type: 'paragraph',
        content: 'In at posuere odio. Morbi at eros pellentesque, efficitur magna et, gravida nisl. Morbi volutpat tortor placerat arcu efficitur sagittis. Nulla vulputate tincidunt ante non commodo. Donec convallis purus scelerisque ex gravida, sed auctor sapien accumsan. Morbi lobortis commodo molestie. Ut eleifend tellus a ligula sodales, in ultricies ex fringilla. Quisque ac magna ac ante laoreet euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum ac semper turpis, tristique cursus nisl. Pellentesque cursus vitae erat non malesuada. Nulla varius est ligula, ut maximus ligula fringilla id. Duis rhoncus tincidunt bibendum. Donec lorem massa, sodales vel elementum vitae, efficitur vel nisi. Maecenas malesuada ut ipsum quis commodo.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 51,
        element_id: 66,
        type: 'paragraph',
        content: 'Aliquam volutpat a diam eu luctus. Aliquam rhoncus, urna dapibus sagittis pretium, lacus quam posuere turpis, porttitor aliquam metus ipsum vel velit. Aliquam porta nisl eros, vel consequat turpis maximus vitae. Duis a feugiat leo, eget semper turpis. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer ullamcorper fermentum felis, eu rutrum dui pulvinar congue. Duis id diam condimentum, feugiat ipsum eu, sagittis arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 52,
        element_id: 67,
        type: 'title1',
        content: 'Introduction',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 53,
        element_id: 68,
        type: 'title2',
        content: 'Les accords',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 54,
        element_id: 69,
        type: 'paragraph',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor mi egestas augue faucibus luctus. Mauris a gravida sem. Aenean non convallis nunc, nec consequat purus. Nam sed leo in lacus mattis lacinia ut ac augue. Vivamus mollis tellus a tempus luctus. Phasellus ornare et dui sit amet tempor. Nullam laoreet condimentum dolor in ullamcorper. Sed molestie, lectus eget dignissim lobortis, felis leo mattis sem, a vestibulum mi felis non neque. Morbi imperdiet orci sit amet risus suscipit, vel pretium augue rutrum. Nunc ullamcorper justo ac sem pellentesque porttitor. Ut at pellentesque mauris. Cras metus sapien, molestie sit amet orci in, tincidunt ullamcorper arcu. Aliquam consectetur efficitur magna sit amet blandit. Donec id velit iaculis, tincidunt lectus at, dapibus massa. Sed dictum sed lorem non sagittis. Maecenas pulvinar nibh eu sapien finibus, consectetur aliquam sem tempus.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 55,
        element_id: 70,
        type: 'title2',
        content: 'Les gammes',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 56,
        element_id: 71,
        type: 'paragraph',
        content: 'Curabitur varius, est sit amet placerat porttitor, felis tellus condimentum lacus, a tempus lorem odio a odio. Nulla efficitur, ligula at pharetra pharetra, est metus placerat lacus, vel faucibus tortor risus et neque. Fusce vitae pellentesque sem. Donec quis eleifend ligula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc porta nunc nec felis gravida euismod. Maecenas non fermentum enim, vitae convallis sem. In rhoncus risus vitae rutrum laoreet. Nullam ullamcorper dictum ipsum, laoreet bibendum elit. Nam eleifend fringilla velit, convallis lobortis leo. Nam a cursus enim. Mauris varius malesuada metus, a finibus turpis. Vivamus facilisis tristique nunc non fringilla. Maecenas convallis quam et dui dignissim dapibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 57,
        element_id: 72,
        type: 'paragraph',
        content: 'Vestibulum ex tortor, venenatis nec sem ut, iaculis pharetra ipsum. Etiam aliquet quam suscipit dolor pulvinar, in fringilla lorem efficitur. Vivamus congue risus a neque porttitor convallis. Sed bibendum tortor nec varius feugiat. Donec consectetur tortor neque, id aliquet quam porttitor fermentum. Integer sem urna, dictum ut finibus eget, sagittis eu mauris. Nulla ut gravida est. Donec tincidunt eros at vestibulum mollis. Etiam aliquam tortor id massa finibus, ac posuere risus iaculis. Cras lobortis lacus vitae lectus rhoncus, eu vehicula diam facilisis. Sed placerat feugiat ante. Proin convallis metus accumsan, rhoncus nisi at, sollicitudin nunc. Proin mauris eros, aliquet at purus id, blandit consequat sem. Vestibulum nisl turpis, commodo nec lobortis sit amet, vehicula id nisl.',
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
    ], {})
  },

  async down (queryInterface, Sequelize) {
    return queryInterface.bulkDelete('text', null, {});
  }
}