"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("image", [
      { 
        id: 1,
        element_id: 2,
        legend: null,
        source: '51867168665.jpg',
        alternative: "Dessin orangé d'un écran d'ordinateur avec le logo java script en haut à gauche.",
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 2,
        element_id: 6,
        legend: "Exemples de blocs conditionnels if",
        source: '1918618151.jpg',
        alternative: "Exemple de code java script permettant d'illustrer les blocs conditionnels if.",
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 3,
        element_id: 8,
        legend: "Cycle lunaire",
        source: '1765445188902-86428101.jpg',
        alternative: "Schéma explicatif du cycle lunaire. A droite il y a le soleil, à gauche il y a la terre avec autour la lune à chacune des phases de son cycle.",
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 4,
        element_id: 16,
        legend: "Les modes de cuisson",
        source: '1765446285204-208517829.jpg',
        alternative: "Présentation des modes de cuisson avec une image représentant le mode de cuisson et le nom en dessous. De la gauche vers la droite, on trouve les modes sauter, griller, braiser, rôtir et pocher.",
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 5,
        element_id: 20,
        legend: "Anatomie d'une guitare",
        source: '1765446780627-197264799.jpg',
        alternative: "A gauche, en haut, le sillet de tête, la barrette ou frette, la touche, le talon, le fond qui est le dos de l'instrument, la rosace, les 6 cordes, l'éclisse, le sillet de chevalet, la table d'harmonie, le chevalet. A droite, la tête, le manche, la caisse.",
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 6,
        element_id: 26,
        legend: "Les 5 type de goût",
        source: '1765447153365-655486301.jpg',
        alternative: "Les différents goûts avec un aliment, le nom du goût et la localisation des papilles gustatives. De gauche à droite, il y a un gâteau pour le sucré, un citron pour l'acide, un bretzel pour le salé, un brocoli pour l'amer et un jambon pour l'umami.",
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 7,
        element_id: 29,
        legend: "Exemple de code HTML",
        source: '1765447385191-792798444.jpg',
        alternative: "Exemple de code HTML dans un éditeur de code.",
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 8,
        element_id: 35,
        legend: "Exemple de code CSS",
        source: '1765447765657-246973910.jpg',
        alternative: "Exemple de code CSS dans un éditeur de code.",
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 9,
        element_id: 39,
        legend: "Hors d'oeuvre",
        source: '1765448641896-963367750.jpg',
        alternative: "Sept bouchées de filet mignon avec du persil sur le dessus et un cure-dent.",
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 10,
        element_id: 40,
        legend: "Exemples d'outils du jardinier",
        source: '1765448145196-546227071.jpg',
        alternative: "Les outils de gauche à droite, de haut en bas : la cisaille,....",
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 11,
        element_id: 47,
        legend: "Anatomie d'un piano",
        source: '1765448391291-242370102.jpg',
        alternative: "A gauche de haut en bas, il y a les cordes, le clavier, les chevilles. A droite, de haut en bas, il y a le cadre, la table d'harmonie, les marteaux. Un ligne en pointillés traverse le piano, c'est la coupe.",
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 12,
        element_id: 51,
        legend: "Anatomie d'une assiette",
        source: '1765448519408-326116669.jpg',
        alternative: "A droite de l'assiette de haut en bas, il y a l'aile et le bassin. Dans l'assiette, écrit à l'horizontal, il y a le diamètre du bassin et écrit à la verticale, il y a le diamètre de l'assiette.",
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 13,
        element_id: 54,
        legend: "Entrée",
        source: '1765448867140-72882194.jpg',
        alternative: "Photo d'une entrée de coquilles saint jacques étagées sur de fines galettes dans une assiette au bord noir. Sur le fond flouté de la photo, on observe des boules de Noël.",
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 14,
        element_id: 57,
        legend: "Plat principal",
        source: '1765449065528-44016830.jpg',
        alternative: "Photo d'une cocotte en fonte sur une table ayant une nappe bleue. Dans la cocotte, il y a une volaille avec des pommes de terre grenailles autour. En haut à gauche de la cocotte, il y a une spatule en bois avec une pomme de terre dessus.",
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
      { 
        id: 15,
        element_id: 59,
        legend: "Un dessert : le bavarois",
        source: '1765449203997-899379492.jpg',
        alternative: "Photo d'un bavarois aux fruits rouge avec trois fraises dessus et des fraises coupées en deux tout autour. Il manque une part de gâteau. Le tout est dans une assiette blanche sur une table en bois.",
        createdAt: new Date(),
        updatedAt: new Date(),
        createdBy: 1,
        updatedBy: null,
      },
    ], {})
  },

  async down (queryInterface, Sequelize) {
    return queryInterface.bulkDelete('image', null, {});
  }
}